name: Run Bash Program

on:
  push:
    branches:
      - feature/5/pynequa-add-auto-build-and-test-scripts  # Change this to your main branch name, e.g., master, if it's different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Bash environment
        run: |
          sudo apt-get update
          sudo apt-get install -y bash

      - name: Make build script executable
        run: chmod +x install.sh

      - name: Run the Bash script
        run: ./install.sh
